default_context:
  project_name: 'Graduation Design'
  project_slug: 'graduation-design'
  domain_main: 'beishangongzi.top'
  domain_staging: 'stag.beishangongzi.top'
  docker_swarm_stack_name_main: 'beishangongzi-top'
  docker_swarm_stack_name_staging: 'stag-beishangongzi-top'
  secret_key: 'qwerasdf'
  first_superuser: 'zhangruibin021@gmail.com'
  first_superuser_password: 'qwerasdf'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.beishangongzi.top", "https://stag.beishangongzi.top", "https://beishangongzi.top", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '25'
  smtp_host: 'smtp.126.com'
  smtp_user: 'andyelizabeth021@126.com'
  smtp_password: 'GYCGZWPNNFPUXCPC'
  smtp_emails_from_email: 'andyelizabeth021@126.com'
  postgres_password: 'qwerasdf'
  pgadmin_default_user: 'zhangruibin021@gmail.com'
  pgadmin_default_user_password: 'qwerasdf'
  traefik_constraint_tag: 'beishangongzi.top'
  traefik_constraint_tag_staging: 'stag.beishangongzi.top'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:qwerasdf'
  sentry_dsn: ''
  docker_image_prefix: 'graduation_andy_'
  docker_image_backend: 'graduation_andy_backend'
  docker_image_celeryworker: 'graduation_andy_celeryworker'
  docker_image_frontend: 'graduation_andy_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
